ALTER TABLE "MemoryEntity" ADD COLUMN "forgottenAt" TIMESTAMP(3);
ALTER TABLE "MemoryFact" ADD COLUMN "kind" TEXT NOT NULL DEFAULT 'STATE', ADD COLUMN "evidence" TEXT, ADD COLUMN "withdrawnAt" TIMESTAMP(3);
