<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue"; import { api } from "../api"; import { Brain, Pencil, Trash2 } from "lucide-vue-next";
type Fact={id:string;attribute:string;value:string;createdAt:string;supersededById?:string;userEdited:boolean;kind?:string;evidence?:string;withdrawnAt?:string;sourceType?:string;sourceId?:string;effectiveAt?:string;observedAt?:string}; type Entity={id:string;type:string;canonicalName:string;facts:Fact[]}; const memories=ref<Entity[]>([]);
const tasks=ref<Array<{id:string;sourceType:string;sourceId:string;status:string;errorMessage?:string}>>([]);const worker=ref("");const error=ref("");const loadError=ref("");const busy=ref(false);let timer:ReturnType<typeof setInterval>|undefined;let loading=false;
async function load(){if(loading)return;loading=true;try{const [entities,results,health]=await Promise.all([api<Entity[]>("/memories"),api<typeof tasks.value>("/memories/tasks"),api<{worker:string}>("/health/ready")]);memories.value=entities;tasks.value=results;worker.value=health.worker;loadError.value="";}catch(e){loadError.value=(e as Error).message;}finally{loading=false;}}
async function retry(id:string){try{await api(`/memories/tasks/${id}/retry`,{method:"POST"});await load();}catch(e){error.value=(e as Error).message;}} async function edit(f:Fact){
 if(busy.value)return;const value=prompt("修改记忆",f.value);if(value===null||value===f.value)return;error.value="";
 if(!value.trim()){error.value="记忆内容不能为空";return;}busy.value=true;
 try{await api(`/memories/facts/${f.id}`,{method:"PATCH",body:JSON.stringify({value})});await load();}catch(e){error.value=`修改失败：${(e as Error).message}`;}finally{busy.value=false;}
}
async function remove(id:string){
 if(busy.value||!confirm("确认忘记该实体？全部记忆将删除，并停止从后台任务重新提取该实体。"))return;
 busy.value=true;error.value="";try{await api(`/memories/${id}`,{method:"DELETE"});await load();}catch(e){error.value=`删除失败：${(e as Error).message}`;}finally{busy.value=false;}
} onMounted(()=>{void load();timer=setInterval(()=>void load(),5000);});onUnmounted(()=>{if(timer)clearInterval(timer);});
</script>
<template><div class="page"><header class="page-header"><div><h1>记忆管理</h1><p>系统自动提取的人物、时间、地点、主题与关系</p></div></header><p v-if="error||loadError" class="error" role="alert">{{error||loadError}}</p><p v-if="worker==='offline'" class="error">后台 Worker 离线，任务暂未消费；请运行 start.cmd 恢复服务。</p><details v-if="tasks.length"><summary>记忆整理任务 · {{tasks.length}} 条最近记录</summary><div v-for="task in tasks" :key="task.id"><small>{{task.sourceType}} · {{task.sourceId}} · {{task.status==='READY'?'抽取完成（可能没有可保存事实）':task.status==='FAILED'?'抽取失败':'抽取中'}} {{task.errorMessage}}</small><button v-if="task.status==='FAILED'" @click="retry(task.id)">重试抽取</button></div></details><div v-if="!memories.length" class="big-empty"><Brain/><h3>还没有长期记忆</h3><p>完成对话或会议分析后，相关事实会在后台自动整理。</p></div><div class="memory-grid"><article v-for="entity in memories" :key="entity.id" class="memory-card"><header><span class="badge">{{entity.type}}</span><strong>{{entity.canonicalName}}</strong><button class="icon danger" title="删除记忆" :disabled="busy" @click="remove(entity.id)"><Trash2 :size="16"/></button></header><div v-for="fact in entity.facts" :key="fact.id" :class="['fact',{old:fact.supersededById||fact.withdrawnAt}]"><div><small>{{fact.attribute}}</small><p>{{fact.value}}</p><small>{{fact.withdrawnAt?"已撤回":fact.supersededById?"历史版本":fact.kind==='EVENT'?"历史事件":"当前状态"}} · {{fact.sourceType}}</small><small v-if="fact.effectiveAt">事件时间：{{new Date(fact.effectiveAt).toLocaleString()}}</small><details><summary>来源与证据</summary><small>来源编号：{{fact.sourceId}}</small><p>{{fact.evidence||"旧记录没有保存原文证据"}}</p></details></div><button v-if="!fact.supersededById&&!fact.withdrawnAt" class="icon" title="编辑记忆" :disabled="busy" @click="edit(fact)"><Pencil :size="15"/></button></div></article></div></div></template>
